name: Bug Report (Plugin Two)
description: Create a bug report for Plugin Two
title: "[Plugin Two] "
labels: ["bug", "Plugin: Two"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
