name: Bug Report (Plugin Three)
description: Create a bug report for Plugin Three
title: "[Plugin Three] "
labels: ["bug", "Plugin: Three"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
