name: Bug Report (Firebridge for VS Code)
description: Create a bug report for Plugin Two
title: "[Firebridge for VS Code] "
labels: ["bug", "Plugin: VS Code"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
